[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
# runner = "probe-rs run --chip RP2040"
runner = "elf2uf2-rs -d -s"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
