---

name: Build and Release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: Semver level to bump
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      app: ${{ steps.new_app.outputs.new_version }}
      new_ref: ${{ steps.commit.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4

      - name: Current versions
        id: version
        run: echo "app=$(grep -oP '(?<=^version = ")[\w\.]+' Cargo.toml)" >> $GITHUB_OUTPUT

      - uses: actions-ecosystem/action-bump-semver@v1
        id: new_app
        with:
          current_version: ${{ steps.version.outputs.app }}
          level: ${{ github.event.inputs.bump }}

      - name: Update Cargo.toml
        run: sed -i "s/^version = .*/version = \"${{ steps.new_app.outputs.new_version }}\"/" Cargo.toml

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Bump version to ${{ steps.new_app.outputs.new_version }}
          file_pattern: Cargo.toml

  build:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump.outputs.new_ref }}

      - name: Install Rust toolchain
        id: rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ steps.rust.outputs.cachekey }}

      - name: Compile
        run: |
          cargo build --release

      - name: Build UF2
          cargo install elf2uf2-rs
          elf2uf2-rs target/thumbv6m-none-eabi/debug/tea-blower tea-blower.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: binary
          path: tea-blower.uf2

  release:
    runs-on: ubuntu-latest
    needs:
      - bump
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: binary

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Tea Blower v${{ needs.bump.outputs.app }}
          tag_name: v${{ needs.bump.outputs.app }}
          target_commitish: ${{ needs.bump.outputs.new_ref }}
          generate_release_notes: true
          make_latest: true
          files: tea-blower.uf2
